#!/usr/bin/env node

/**
 * Build Configuration Script
 * This script injects environment variables into the frontend config.js file
 * Usage: node build-config.js [environment]
 * 
 * Environment options:
 * - development (default)
 * - production
 * - staging
 */

const fs = require('fs');
const path = require('path');

// Get environment from command line argument
const environment = process.argv[2] || 'development';

// Load environment variables
require('dotenv').config({ path: './config.env' });

// Configuration for different environments
const configs = {
    development: {
        API_BASE_URL: process.env.API_BASE_URL || 'http://localhost:7000/api',
        FRONTEND_URL: process.env.FRONTEND_URL || 'http://localhost:7000'
    },
    staging: {
        API_BASE_URL: process.env.API_BASE_URL || 'https://staging-api.yourapp.com/api',
        FRONTEND_URL: process.env.FRONTEND_URL || 'https://staging.yourapp.com'
    },
    production: {
        API_BASE_URL: process.env.API_BASE_URL || 'https://api.yourapp.com/api',
        FRONTEND_URL: process.env.FRONTEND_URL || 'https://yourapp.com'
    }
};

// Get current config
const config = configs[environment];

if (!config) {
    console.error(`Unknown environment: ${environment}`);
    console.log('Available environments: development, staging, production');
    process.exit(1);
}

// Generate the config.js content
const configContent = `// Frontend Configuration - Generated for ${environment} environment
// This file is auto-generated by build-config.js

// API Configuration
window.API_BASE = '${config.API_BASE_URL}';
window.FRONTEND_URL = '${config.FRONTEND_URL}';

// Helper function to get API URL
window.getApiUrl = function(endpoint) {
    return \`\${window.API_BASE}\${endpoint.startsWith('/') ? endpoint : '/' + endpoint}\`;
};

// Helper function to get upload URL
window.getUploadUrl = function(imagePath) {
    if (!imagePath) return '';
    const baseUrl = window.FRONTEND_URL;
    return \`\${baseUrl}/uploads/\${imagePath}\`;
};

// Helper function to get full URL
window.getFullUrl = function(path) {
    return \`\${window.FRONTEND_URL}\${path.startsWith('/') ? path : '/' + path}\`;
};

// Export for module systems (if needed)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        API_BASE: window.API_BASE,
        FRONTEND_URL: window.FRONTEND_URL,
        getApiUrl: window.getApiUrl,
        getUploadUrl: window.getUploadUrl,
        getFullUrl: window.getFullUrl
    };
}
`;

// Write the config file
const configPath = path.join(__dirname, 'frontend', 'js', 'config.js');
fs.writeFileSync(configPath, configContent);

console.log(`✅ Configuration generated for ${environment} environment`);
console.log(`📁 Config file: ${configPath}`);
console.log(`🔗 API Base URL: ${config.API_BASE_URL}`);
console.log(`🌐 Frontend URL: ${config.FRONTEND_URL}`); 