// Frontend Configuration - Generated for development environment
// This file is auto-generated by build-config.js

// API Configuration
window.API_BASE = 'http://localhost:7000/api';
window.FRONTEND_URL = 'http://localhost:7000';

// Helper function to get API URL
window.getApiUrl = function(endpoint) {
    return `${window.API_BASE}${endpoint.startsWith('/') ? endpoint : '/' + endpoint}`;
};

// Helper function to get upload URL
window.getUploadUrl = function(imagePath) {
    if (!imagePath) return '';
    const baseUrl = window.FRONTEND_URL;
    return `${baseUrl}/uploads/${imagePath}`;
};

// Helper function to get full URL
window.getFullUrl = function(path) {
    return `${window.FRONTEND_URL}${path.startsWith('/') ? path : '/' + path}`;
};

// Export for module systems (if needed)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        API_BASE: window.API_BASE,
        FRONTEND_URL: window.FRONTEND_URL,
        getApiUrl: window.getApiUrl,
        getUploadUrl: window.getUploadUrl,
        getFullUrl: window.getFullUrl
    };
}
